# Generated by Django 4.2.30 on 2026-04-30 23:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('audience', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, choices=[('tech', 'Technology'), ('health', 'Health & Wellness'), ('education', 'Education'), ('finance', 'Finance & Fintech'), ('retail', 'Retail & E-commerce'), ('food', 'Food & Beverage'), ('travel', 'Travel & Hospitality'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('GO', 'Go'), ('CAUTION', 'Caution'), ('NO-GO', 'No-Go')], max_length=10)),
                ('summary', models.TextField()),
                ('market_score', models.IntegerField()),
                ('feasibility_score', models.IntegerField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('opportunities', models.JSONField(default=list)),
                ('threats', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('next_steps', models.JSONField(default=list)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generation_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='validator.ideasubmission')),
            ],
        ),
    ]
